Hw7
DenysCherkasov/A-Level pull request #7
Opened 2022-11-12 20:07 UTC by DenysCherkasov

2022-11-13 21:10 UTC, Fabolo12 requested changes

2022-11-13 21:10 UTC, Fabolo12 commented on src/main/java/com/cherkasov/model/Car.java
> +    private int enginePower;
Это должен быть обьект Engine, а не его поля

2022-11-13 21:21 UTC, DenysCherkasov commented
Я сначала так и сделал, а потом передел, чтобы метод принят мог отобразить
данные в консоль. Так неправильно?
То есть просто переделать обратно на объект здесь?

Вс, 13 нояб. 2022 г. в 23:10, Valerii ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/main/java/com/cherkasov/model/Car.java
> <https://github.com/DenysCherkasov/A-Level/pull/7#discussion_r1020964205>:
>
> > +    private String engineType;
>
> +    private int enginePower;
>
>
> Это должен быть обьект Engine, а не его поля
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DenysCherkasov/A-Level/pull/7#pullrequestreview-1178298278>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3Z4SZOQAVGHVQZTCP6XG3DWIFKNLANCNFSM6AAAAAAR6PAQTI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-18 23:23 UTC, Fabolo12 approved these changes

2022-11-23 18:11 UTC, closed without merging